# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic_model.proto',
  package='model_grpc_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13generic_model.proto\x12\x12model_grpc_service\"\x07\n\x05\x65mpty\"\xb4\x01\n\x05model\x12\x16\n\x0equalified_name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rmajor_version\x18\x04 \x01(\x11\x12\x15\n\rminor_version\x18\x05 \x01(\x11\x12\x12\n\ninput_type\x18\x06 \x01(\t\x12\x13\n\x0boutput_type\x18\x07 \x01(\t\x12\x11\n\toperation\x18\x08 \x01(\t\"\"\n\x0f\x61\x63k_modelupdate\x12\x0f\n\x07updated\x18\x01 \x01(\x08\"$\n\x15generic_msg_dataframe\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xcd\x02\n\x11GenericMLServices\x12l\n\x18\x43onfigureModelParameters\x12).model_grpc_service.generic_msg_dataframe\x1a#.model_grpc_service.ack_modelupdate\"\x00\x12\x64\n\nTrainModel\x12).model_grpc_service.generic_msg_dataframe\x1a).model_grpc_service.generic_msg_dataframe\"\x00\x12\x64\n\nInferModel\x12).model_grpc_service.generic_msg_dataframe\x1a).model_grpc_service.generic_msg_dataframe\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='model_grpc_service.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=50,
)


_MODEL = _descriptor.Descriptor(
  name='model',
  full_name='model_grpc_service.model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='qualified_name', full_name='model_grpc_service.model.qualified_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='model_grpc_service.model.display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='model_grpc_service.model.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='major_version', full_name='model_grpc_service.model.major_version', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minor_version', full_name='model_grpc_service.model.minor_version', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_type', full_name='model_grpc_service.model.input_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_type', full_name='model_grpc_service.model.output_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='model_grpc_service.model.operation', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=233,
)


_ACK_MODELUPDATE = _descriptor.Descriptor(
  name='ack_modelupdate',
  full_name='model_grpc_service.ack_modelupdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='updated', full_name='model_grpc_service.ack_modelupdate.updated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=269,
)


_GENERIC_MSG_DATAFRAME = _descriptor.Descriptor(
  name='generic_msg_dataframe',
  full_name='model_grpc_service.generic_msg_dataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='model_grpc_service.generic_msg_dataframe.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['model'] = _MODEL
DESCRIPTOR.message_types_by_name['ack_modelupdate'] = _ACK_MODELUPDATE
DESCRIPTOR.message_types_by_name['generic_msg_dataframe'] = _GENERIC_MSG_DATAFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'generic_model_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.empty)
  })
_sym_db.RegisterMessage(empty)

model = _reflection.GeneratedProtocolMessageType('model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'generic_model_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.model)
  })
_sym_db.RegisterMessage(model)

ack_modelupdate = _reflection.GeneratedProtocolMessageType('ack_modelupdate', (_message.Message,), {
  'DESCRIPTOR' : _ACK_MODELUPDATE,
  '__module__' : 'generic_model_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.ack_modelupdate)
  })
_sym_db.RegisterMessage(ack_modelupdate)

generic_msg_dataframe = _reflection.GeneratedProtocolMessageType('generic_msg_dataframe', (_message.Message,), {
  'DESCRIPTOR' : _GENERIC_MSG_DATAFRAME,
  '__module__' : 'generic_model_pb2'
  # @@protoc_insertion_point(class_scope:model_grpc_service.generic_msg_dataframe)
  })
_sym_db.RegisterMessage(generic_msg_dataframe)



_GENERICMLSERVICES = _descriptor.ServiceDescriptor(
  name='GenericMLServices',
  full_name='model_grpc_service.GenericMLServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=310,
  serialized_end=643,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConfigureModelParameters',
    full_name='model_grpc_service.GenericMLServices.ConfigureModelParameters',
    index=0,
    containing_service=None,
    input_type=_GENERIC_MSG_DATAFRAME,
    output_type=_ACK_MODELUPDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainModel',
    full_name='model_grpc_service.GenericMLServices.TrainModel',
    index=1,
    containing_service=None,
    input_type=_GENERIC_MSG_DATAFRAME,
    output_type=_GENERIC_MSG_DATAFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InferModel',
    full_name='model_grpc_service.GenericMLServices.InferModel',
    index=2,
    containing_service=None,
    input_type=_GENERIC_MSG_DATAFRAME,
    output_type=_GENERIC_MSG_DATAFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERICMLSERVICES)

DESCRIPTOR.services_by_name['GenericMLServices'] = _GENERICMLSERVICES

# @@protoc_insertion_point(module_scope)
